---
title: Help POC
timezone: UTC
collections:
  help:
    title: Help
    output: true
    permalink: "/:title/"
  homehealthhelp:
    title: HomeHealthHelp
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: 
description: 
baseurl: ''
url: ''
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
